mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.faceworld.spring.cloud.auth
server:
  port: 6868
  servlet:
    path: /auth
spring:
  application:
    name: faceworld-auth
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 1
      max-active: 20
      min-idle: 1
      password: Face@2018
      test-on-borrow: true
      url: jdbc:mysql://47.98.253.106:3306/faceworld_admin?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
security:
  oauth2:
    resource:
      id: faceworld-auth
      #指定用户信息地址
      user-info-uri: localhost:9201/auth/oauth/token
      prefer-token-info: false